profiles:
  dm_arm_gray:
    core:
      package: dm_arm_description
      config: config/core/gray.yaml
    hardware:
      plugin: serial_arm_hardware_damiao
      config_package: dm_arm_description
      config: config/hardware.yaml
    description:
      package: dm_arm_description
      urdf: model/gray/urdf/dm_arm_no_gripper.urdf
      ros2_control_xacro: model/gray/urdf/dm_arm.ros2_control.xacro
    controllers:
      package: dm_arm_description
      config: config/ros2_controllers.yaml
    moveit:
      package: dm_arm_no_gripper

  dm_arm_white:
    core:
      package: dm_arm_description
      config: config/core/white.yaml
    hardware:
      plugin: serial_arm_hardware_damiao
      config_package: dm_arm_description
      config: config/hardware.yaml
    description:
      package: dm_arm_description
      urdf: model/white/urdf/dm_arm.urdf
      ros2_control_xacro: model/white/urdf/dm_arm.ros2_control.xacro
    controllers:
      package: dm_arm_description
      config: config/ros2_controllers.yaml
    moveit:
      package: dm_arm_with_gripper
