profiles:
  dm_arm_gray:
    core:
      package: dm_arm_description
      config: config/dm_arm_gray.yaml
    hardware:
      plugin: serial_arm_hardware_damiao
      config_package: dm_arm_description
      config: config/dm_arm_damiao.yaml
    description:
      package: dm_arm_description
      model: dm_arm_gray
      xacro: model/dm_arm_gray/urdf/dm_arm.urdf.xacro
      ros2_control_xacro: model/dm_arm_gray/urdf/dm_arm.ros2_control.xacro
    controllers:
      package: dm_arm_description
      config: config/ros2_controllers.yaml
    moveit:
      package: dm_arm_no_gripper

  dm_arm_white:
    core:
      package: dm_arm_description
      config: config/dm_arm_white.yaml
    hardware:
      plugin: serial_arm_hardware_damiao
      config_package: dm_arm_description
      config: config/dm_arm_damiao.yaml
    description:
      package: dm_arm_description
      model: dm_arm_white
      xacro: model/dm_arm_white/urdf/dm_arm.urdf.xacro
      ros2_control_xacro: model/dm_arm_white/urdf/dm_arm.ros2_control.xacro
    controllers:
      package: dm_arm_description
      config: config/ros2_controllers.yaml
    moveit:
      package: dm_arm_with_gripper
